language: cpp

compiler:
    - gcc
    - clang
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - cmake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvtk5-dev
  
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
