language: cpp

compiler:
    - gcc
    - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvtk5-dev libboost-all-dev
  
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
